development:
  api_key:    "782595142739738"
  api_secret: "DGUwO7jBy-ISKnuo3RFD2uyFL1w"
  cloud_name: "dxiwc9rv6"
  enhance_image_tag:    true
  static_image_support: false

production:
  cloud_name: "dxiwc9rv6"
  api_key:    "782595142739738"
  api_secret: "DGUwO7jBy-ISKnuo3RFD2uyFL1w"
 